packages:
  - apps/drizzle-run
  - packages/*
  - vscode-extension

patchedDependencies:
  html-to-image: patches/html-to-image+1.11.11.patch

catalog:
  "@tailwindcss/vite": ^4.1.12
  "@types/node": ^22.18.0
  "@types/react": ^19.1.12
  "@types/react-dom": ^19.1.9
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  tailwindcss-animate: ^1.0.7
  tw-animate-css: ^1.3.7
  typescript: ^5.9.2
  vite: ^7.1.3
  vite-tsconfig-paths: ^5.1.4
