name: 🚀 pkg-pr-new
on:
  push:
    paths:
      - "packages/**"
  pull_request:
    paths:
      - "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - run: npx pkg-pr-new publish
